### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by dwilkie** [CodeMonkeyKevin/smpp34#8]
I get this exception when trying to run `trx_example.go` in the examples directory

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x68 pc=0x44d04d]

goroutine 1 [running]:
runtime.panic(0x51e0e0, 0x6a9208)
	/usr/local/go/src/pkg/runtime/panic.c:266 +0xb6
github.com/CodeMonkeyKevin/smpp34.(*Smpp).Write(0xc2100390c0, 0x0, 0x0, 0x4, 0xffffffffffffffff)
	/home/ubuntu/go/src/github.com/CodeMonkeyKevin/smpp34/smpp.go:261 +0x2d
github.com/CodeMonkeyKevin/smpp34.(*Transceiver).Write(0xc2100390c0, 0x0, 0x0, 0x5, 0x541980)
	/home/ubuntu/go/src/github.com/CodeMonkeyKevin/smpp34/transceiver.go:218 +0x42
github.com/CodeMonkeyKevin/smpp34.(*Transceiver).Bind(0xc2100390c0, 0x541980, 0x5, 0x541980, 0x5, ...)
	/home/ubuntu/go/src/github.com/CodeMonkeyKevin/smpp34/transceiver.go:43 +0xa9
github.com/CodeMonkeyKevin/smpp34.NewTransceiver(0x54a810, 0xe, 0xc80, 0x5, 0xc21001e360, ...)
	/home/ubuntu/go/src/github.com/CodeMonkeyKevin/smpp34/transceiver.go:25 +0x1b5
main.main()
	/home/ubuntu/smpp34/examples/trx_example.go:21 +0x224
```

**Comment by CodeMonkeyKevin** [comment]
Sorry I missed this issue. Are you still having this issue?
